### ISSUE TITLE
Not working in Safari and Mobile Browsers

### ISSUE THREAD

**Issue by adnanraja** [rainabba/jquery-table2excel#15]
This plugins works fine in Chrome, IE and firefox on my desktop, but doesn't work in Safari and Android default mobile browser. By doesn't work, I mean, nothing happens on clicking Export button and no error in console as well.

**Comment by adnanraja** [comment]
It wasn't even working in Firefox, but I made following changes to make it work in firefox:

link = e.uri + e.base64(e.format(fullTemplate, e.ctx));
				a = document.createElement("a");
				a.download = getFileName(e.settings);
				a.href = link;
                                document.body.appendChild(a); //new line added
                                a.click();
                                document.body.removeChild(a);  //new line added

**Comment by adnanraja** [comment]
Any way to fix this?

**Comment by rivkadr** [comment]
Any fix to this?

**Comment by rainabba** [comment]
@adnanraja Submit a PR with the fix and I'll accept. Please be sure to test with Chrome, IE and Safari also to ensure your solution doesn't break other browsers.

**Comment by binalpanchal** [comment]
Still it's not working in Mac safari and chrome browser and also in iPad safari browser. 
Is there any fix for this?

**Comment by rainabba** [comment]
@binalpanchal "Not working" isn't helpful. You'll need to provide more details and error messages if you want anyone else to put any effort in to the issue that YOU are seeing. When you've got more details, please open a new issue also.
