### ISSUE TITLE
Adding HTML content to head

### ISSUE THREAD

**Issue by erayaydin** [rainabba/jquery-table2excel#17]
Hello,
My customer wants some headings to excel. For example:

``` php
<div id="table2excel">
<h1>Heading</h1>
<table>
...
</table>
</div>
```

I think these support not good for jquery-table2excel. Because its **table** to excel. But, how can I do that?

**Comment by ferman2147** [comment]
See if you can put your heading inside a table row and style that row's borders to bi invisible. If you can't put heading tags inside the row, then you can style the row to look like a heading.

**Comment by erayaydin** [comment]
Thank you for comment @ferman2147 , But `text align` and some CSS stuffs don't work with **rainabba/jquery-table2excel**

**Comment by ferman2147** [comment]
You know you don't have to use text-align, if that's the only case. You can style other ways and get the look you want. I haven't tried, but if something like the code below doesn't work, right now I can't come up with any other ideas, sorry for that. But if you find, or can't find a solution, please let us know so we can work on it whenever we find somet time for it.

```css
.myHeading{
border:none;
font: 18px Roboto;
padding-left:10%;
}
```
```html
<tr class="myHeading">Heading 1</tr>
```
