### ISSUE TITLE
giving a userdefined name to the file

### ISSUE THREAD

**Issue by nairvishal** [rainabba/jquery-table2excel#2]
Great plugin bro. Is it possible to give a default user defined file name . Right now it directly shows 'download' as the name of the file.One more thing what in the case of two tables.How to export both the tables in one file ? I think giving them a common class and then calling with class instead of id won't work , right ?

**Comment by erayaydin** [comment]
:+1:  Its will good

**Comment by rainabba** [comment]
narivshal: As soon as I can figure out to how access all the elements of the selector which the plugin is called on, I'll have an update that provides multiple table functionality. Kinda stuck on this bit for now though.

As for the filename, I think that's a function of the browser and I don't know how to control that yet or if it can be controlled.

**Comment by erayaydin** [comment]
You can create an a element and set "download" parameter. I fixed with this method:

```
// tableToExcel method of plugin:
var link = e.uri + e.base64(e.format(e.template, e.ctx));
var a = document.createElement("a");
a.download = "Fiyat Listesi.xls";
a.href = link;
a.click();
```

**Comment by rainabba** [comment]
I'll add the suggestion from erayaydin to the README.md for others' benefit, but this is an implementation detail, not the plugin itself so I'm going to close the issue.

**Comment by rainabba** [comment]
Implementing as an option

**Comment by erayaydin** [comment]
Thats awesome! Thank you :smile:
