### ISSUE TITLE
Issue with xlsx - xls works

### ISSUE THREAD

**Issue by olimortimer** [rainabba/jquery-table2excel#25]
I've found that outputting the file as a xlsx creates a corrupt file / not recognised properly by Excel or OpenOffice / LibreOffice.

Changing the output to xls works fine, and it can be opened correctly.

You might want to allow people to specify the extensions when passing 'filename', as they might find xlsx doesn't always work.

**Comment by Gaohaoyang** [comment]
I got same problem.
@olimortimer How do you fix it?

I use Chrome47, Office 2015, Windows 10

**Comment by olimortimer** [comment]
Try changing the output file extension from xlsx to xls

**Comment by Gaohaoyang** [comment]
Thanks, I did this

**Comment by rainabba** [comment]
@Gaohaoyang Did that change do what you wanted?

**Comment by olimortimer** [comment]
I thought it had solved my issue (Mac OSX, using Libre Office), but I've reports from a client that the XLS won't open on their Windows Microsoft Office

**Comment by rainabba** [comment]
My experience is that .xls won't open at all, but .xlsx will with a warning so I'm going to close this. Keep in mind that this is a hack so it likely won't work in a consistent manner.
