### ISSUE TITLE
how to change excel sheet name？

### ISSUE THREAD

**Issue by jeffsui** [rainabba/jquery-table2excel#28]
how to change  excel sheet name？
is there any param to support this？

**Comment by nbf2008** [comment]
I also got {table0} in the sheet name tab

**Comment by khamarzama** [comment]
Check out the Jquery finction which is called. 
There is a statement which says:
`name: "Excel Document Name",  
filename: "myFileName",`
Change the above two statements as desired

**Comment by AjayRanganathan** [comment]
[table2Excel.zip](https://github.com/rainabba/jquery-table2excel/files/3475913/table2Excel.zip)

Use Keyword 
sheetName: "Worksheet Name",

and use the table2excel.js
