### ISSUE TITLE
Not working on various browsers

### ISSUE THREAD

**Issue by RommelTJ** [rainabba/jquery-table2excel#30]
This may be related to this issue:  https://github.com/rainabba/jquery-table2excel/issues/15 
I am running OS X El Capitan Version 10.11.2.

In FirefoxDeveloperEdition v45.0a2 (2015-12-20), the table2excel function won't even fire. Nothing happens. I don't even see an entry in the logs. I get the same behavior on regular Firefox (v.33.0.3).

In Chrome  v47.0.2526.106 (64-bit), it will generate a file and prompt me for where to save the file, but when I try to open the file in Excel I get: 
"Excel cannot open this file. The file format or file extension is not valid. Verify that the file has not been corrupted and that the file extension matches the format of the file."

In Safari v.9.0.2 (11601.3.9), the file will be generated and immediately drop into my downloads folder, but it won't have a file extension so I can't open it with Excel out of the box. If I manually rename the file with the ".xls" extension, I can view it in Excel just fine.

**Comment by wilson208** [comment]
Im seeing this issue also. Any fix in the pipeline or will I look into it and submit a pull request if I get a fix?

**Comment by Puppala1** [comment]
Any fix for Safari?

**Comment by RommelTJ** [comment]
After I submitted this issue, the repo owner, @rainabba, has added a disclaimer: https://github.com/rainabba/jquery-table2excel#disclaimer. 

Given that this plugin is only currently supported for Google Chrome, I'm going to go ahead and close this issue.
