### ISSUE TITLE
Please update the code in the /dist folder!

### ISSUE THREAD

**Issue by mitjanikolaus** [rainabba/jquery-table2excel#31]
The code in the "src" and in the "dist" folder are not identical, for example the code in the "dist" folder does not work with firefox, while the one in the "src" folder has a fix for it. (see https://github.com/rainabba/jquery-table2excel/commit/2005265c0fe31ffb04f121d3a06054eb27ab8a31)
So please update the code in the "dist" folder!

**Comment by gioce90** [comment]
Yeah, moreover the code in the dist folder doesn't work with IE.

**Comment by rainabba** [comment]
You guys are welcome to submit a PR if you'd like this done sooner than I'm getting to it. This is OSS.
