### ISSUE TITLE
not working with Internet Explorer

### ISSUE THREAD

**Issue by bernhardhas** [rainabba/jquery-table2excel#33]
On Internet-Explorer 9 and 10 an error occured.
And with Internet-Explorer-11 the result is only one cell with the value "{table0}"

need help ....

thank you !

**Comment by LittleBigThing** [comment]
Same problem here? Any ideas? Would love to help testing...

**Comment by MiniApp** [comment]
i also have a same problem

**Comment by rainabba** [comment]
Duplicate of https://github.com/rainabba/jquery-table2excel/issues/19
