### ISSUE TITLE
Datatables problem

### ISSUE THREAD

**Issue by alexbenza** [rainabba/jquery-table2excel#37]
Hello i've integrated the plugin on a datatables table.. but the bootstrap put the data from table on different pages, when i  try to export using your plugin it extracts only the first page 
![untitled](https://cloud.githubusercontent.com/assets/17921705/14018870/9c4c3f08-f1d8-11e5-9e8a-26c422493ef2.png)

**Comment by rainabba** [comment]
There's nothing this plugin can do about that. Sorry.

**Comment by yupdon** [comment]
If they are sub tables with in the parent, contact me. I have wrote a branch of the main code that works with parent to child data. It's not uploaded yet as i haven't had the time to pretty the code or ensure the main fn()  isn't affected.

**Comment by yupdon** [comment]
Ah no, i see. @alexbenza - all you need to do is to remove the pagination before you export.
