### ISSUE TITLE
demo folder

### ISSUE THREAD

**Issue by AliveDD** [rainabba/jquery-table2excel#53]
i'm clone repo and open /demo folder
and get err in console in chrome
`jquery.table2excel.js:50 Uncaught ReferenceError: p is not defined`

**Comment by AliveDD** [comment]
need to edit index.html to
<script src="../dist/jquery.table2excel.min.js"></script>

**Comment by rainabba** [comment]
Should be resolved with: https://github.com/rainabba/jquery-table2excel/pull/50
