### ISSUE TITLE
Uncaught ReferenceError: msie is not defined

### ISSUE THREAD

**Issue by athanph** [rainabba/jquery-table2excel#7]
Trying this out but having error in Chrome, FF, and IE 11/10. 
Has anyone else got this error?

**Comment by TorbjornB** [comment]
Try the file in the "src" folder if you are using the file from the dist folder.

**Comment by rainabba** [comment]
I'll check and see if I forgot to build for dist and will refresh the repo if that's the case. This is done using grunt if you want to try yourself. The task is the default one.

**Comment by zedissime** [comment]
I've also this issue, any updates?

**Comment by rainabba** [comment]
Just pushed a new commit that addressed a minor typo and dist files are updated from src. Please confirm the original issue is resolved.

**Comment by athanph** [comment]
No error now but the downloaded .xlsx files are empty.

**Comment by zamrokk** [comment]
some error, msie is not defined
