### ISSUE TITLE
Filename not working

### ISSUE THREAD

**Issue by NaveenDA** [rainabba/jquery-table2excel#70]
The download file name is download.xls only.
http://www.jqueryscript.net/demo/Export-Html-Table-To-Excel-Spreadsheet-using-jQuery-table2excel/

**Comment by rainabba** [comment]
I just made some minor updates, refreshed the dist folder and tested the filename option in Chrome 60, FireFox 51, and IE 11. I can confirm it works in those browsers. Please provide more details if you'd like me to reopen this.
