### ISSUE TITLE
export2excel doesnot work after boostrap pop out

### ISSUE THREAD

**Issue by LRMPratiksha** [rainabba/jquery-table2excel#80]
When I export the table without poping out the boostrap modal which open on table row click it works fine but after modal pop out I get an error on exporting to excel.
Uncaught TypeError: $(...).table2excel is not a function
    at HTMLButtonElement.<anonymous> (Reporting.js:21)
    at HTMLButtonElement.dispatch (CodeJquery1.1.0.js:7)
    at HTMLButtonElement.r.handle (CodeJquery1.1.0.js:7)

**Comment by rainabba** [comment]
`$(...).table2excel is not a function` means that even IF your selector `$(...)` is returning a jQuery object, that object isn't exposing the table2excel plugin OR that the plugin isn't properly installed and so you're getting a jQuery object, but still without the plugin exposed.

Set a debug point on that call and then execute your selector and look at the resulting object. That will help you figure out which of those 2 core issues it is.

If you can setup a example of the issue at plnkr or jsfiddle, then I can definitely look into the bug, but without it being recreated I cannot and so far this could be a simple js/jquery logic bug in your code so I need more info.

I'm closing for now so it's not left open, but I will re-open if you provide more info.

**Comment by LRMPratiksha** [comment]
Thank you

It was conflicting with the bootstrap modal pop up plugin so I changed it and now its working.
