### ISSUE TITLE
Remove console.log from dist file

### ISSUE THREAD

**Issue by ribase** [rainabba/jquery-table2excel#95]
Please remove the console.log from your File:

jquery.table2excel.js:91

```
89:
90:   tempRows += "</tr>";
91:   console.log(tempRows);
92:                    
93: });
```

**Comment by rainabba** [comment]
Feel free to submit a PR to have that code removed from this file (which others contribute to more than I these days).  All you need to know here: https://www.youtube.com/watch?v=YTbRzhQju4c
